name: Deploy Docs
on:
  push:
    # branches:
      # - master
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials + Fetch gh-pages Branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        #  git fetch origin gh-pages --depth=1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.8
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install uv
        run: pip install uv
      - name: Install dependencies with uv
        run: |
          uv pip sync

      - name: Deploy Docs
        # run: uv run mike deploy --push --update-alias ${GITHUB_REF#refs/tags/} latest
        run: uv run mkdocs gh-deploy --force