name: Run Python tests

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'bump(release)') == false"
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.7]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry pytest-md pytest-emoji
      - name: Install dependencies with Poetry
        run: poetry install --with=test
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: false
          job-summary: true
